name: timesget
description: Cross Fit Family

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: 0.4.3+1
  firebase_analytics: 5.0.9
  firebase_auth: 0.15.2
  firebase_storage: 3.1.0
  cloud_firestore: 0.13.0+1
  firebase_messaging: 6.0.9
  device_info: 0.4.1+4
  flutter_screenutil: 0.7.0
  page_transition: 1.1.5
  shared_preferences: 0.5.6
  url_launcher: 5.4.1
  cached_network_image: ^2.0.0-rc
  rxdart: 0.22.6
  rx_command: 4.3.3
  rx_widgets: 2.5.0
  built_collection: 4.3.0
  built_value: 7.0.0
  carousel_pro: 1.0.0
  date_format: 1.0.8
  http: 0.12.0+2
  latlong: 0.6.1
  location: 2.3.5
  video_player: 0.10.5
  path_provider: 1.5.1
  camera: 0.5.7+2
  connectivity: 0.4.6+1
  tuple: 1.0.3
  uuid: 2.0.4
  image_picker: 0.6.2+3
  flutter_sound: 1.7.0
  barcode_scan: 1.0.0
  barcode_flutter: 1.1.0
  keyboard_visibility: 0.5.6
  notification_permissions: 0.4.3
  intl: 0.16.0
  flutter_dotenv: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/maps_style.json
    - .env
    # widget's images
    - assets/img/HomeImage.jpg
    - assets/img/AboutImage.jpg
    - assets/img/CheckON.png
    - assets/img/CheckOFF.png
    - assets/img/SettingIcon.png
    - assets/img/RatingEmpty.png
    - assets/img/RatingHalf.png
    - assets/img/RatingFull.png
    - assets/img/Close.png
    - assets/img/Close2.png
    - assets/img/CloseWindow.png
    - assets/img/Logo@1x.png
    - assets/img/Logo@2x.png
    - assets/img/Logo@3x.png
    - assets/img/ScanIcon.png
    - assets/img/MobileCardsImg.png
    - assets/img/OpenCard.png
    - assets/img/Account.png
    - assets/img/AddCard.png
    - assets/img/Back.png
    - assets/img/OpenWindow.png
    - assets/img/Search.png
    - assets/img/Close_Notification.png
    - assets/img/ArrowDown.png
    - assets/img/Notification.png

    - assets/img/MonthNext.png
    - assets/img/MonthPrevious.png

    - assets/img/AppointmentCancel.png
    - assets/img/AppointmentCanceled.png
    - assets/img/AppointmentPassed.png

    - assets/img/Audio.png
    - assets/img/AudioCompleted.png
    - assets/img/Photo.png
    - assets/img/PhotoCompleted.png
    - assets/img/Video.png
    - assets/img/VideoCompleted.png

    - assets/img/Badly.png
    - assets/img/BadlyOFF.png
    - assets/img/Good.png
    - assets/img/GoodOFF.png
    - assets/img/Norm.png
    - assets/img/NormOFF.png

    - assets/img/Placeholder.png
    - assets/img/NotFound.png

    # Bottom Bar Icons
    - assets/img/Home1.png
    - assets/img/Home2.png
    - assets/img/Appointment1.png
    - assets/img/Appointment2.png
    - assets/img/Specialists1.png
    - assets/img/Specialists2.png
    - assets/img/Help1.png
    - assets/img/Help2.png
    - assets/img/Early1.png
    - assets/img/Early2.png
    - assets/img/Comparison.png
    - assets/img/Comparison2.png
    - assets/img/Time1.png
    - assets/img/Time2.png
    - assets/img/Nearby.png
    - assets/img/Nearby2.png
    - assets/img/More1.png
    - assets/img/More2.png

    # Button icon
    - assets/img/IconButton1.png
    - assets/img/IconButton2.png
    - assets/img/IconButton3.png
    - assets/img/IconButton4.png
    - assets/img/IconButton5.png
    - assets/img/IconButton6.png
    - assets/img/IconButton7.png

    # social media
    - assets/img/Facebook.png
    - assets/img/Instagram.png
    - assets/img/Odnoklassniki.png
    - assets/img/VK.png
    - assets/img/Youtube.png

    # lang
    - locale/ru.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geometria
      fonts:
        - asset: assets/fonts/Geometria-Light.ttf
          weight: 100
        # - asset: assets/fonts/Geometria.ttf
        #   weight: 300
        - asset: assets/fonts/Geometria-Medium.ttf
          weight: 500
        # - asset: assets/fonts/Geometria-Medium.ttf
        #   weight: 700
        - asset: assets/fonts/Geometria-Heavy.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
